// Tests for the GameTracer C ABI (c_api/gametracer_c_api.h).
//
// Build and run from the repository root:
//   cmake -S c_api -B build -DGAMETRACER_BUILD_TESTS=ON
//   cmake --build build
//   ctest --test-dir build --output-on-failure

#include "gametracer_c_api.h"

#include <climits>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <vector>

namespace {

int g_failures = 0;

#define CHECK(cond) \
    do { \
        if (!(cond)) { \
            std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
            ++g_failures; \
        } \
    } while (0)

// A normal form game in the layout expected by the C ABI.
struct Game {
    int N;
    std::vector<int> actions;
    std::vector<double> payoffs;  // length N * P, player-major blocks

    int M() const {
        int m = 0;
        for (int p = 0; p < N; ++p) m += actions[p];
        return m;
    }
    int P() const {
        int prod = 1;
        for (int p = 0; p < N; ++p) prod *= actions[p];
        return prod;
    }
    int offset(int p) const {
        int o = 0;
        for (int k = 0; k < p; ++k) o += actions[k];
        return o;
    }
    // profile_index(s) = s0 + s1*a0 + s2*a0*a1 + ...
    int profile_index(const std::vector<int>& s) const {
        int idx = 0, stride = 1;
        for (int p = 0; p < N; ++p) {
            idx += s[p] * stride;
            stride *= actions[p];
        }
        return idx;
    }
    double payoff(int player, const std::vector<int>& s) const {
        return payoffs[static_cast<size_t>(player) * P() + profile_index(s)];
    }
};

// Expected payoff to `player` from pure action `a` when the other players
// play the mixed actions in the flattened profile `x`.
double pure_action_payoff(const Game& g, int player, int a, const double* x) {
    std::vector<int> s(g.N, 0);
    double total = 0.0;
    const int P = g.P();
    for (int idx = 0; idx < P; ++idx) {
        // decode idx into s (first player varying fastest)
        int rem = idx;
        for (int p = 0; p < g.N; ++p) {
            s[p] = rem % g.actions[p];
            rem /= g.actions[p];
        }
        if (s[player] != a) continue;
        double w = 1.0;
        for (int p = 0; p < g.N; ++p) {
            if (p == player) continue;
            w *= x[g.offset(p) + s[p]];
        }
        total += w * g.payoffs[static_cast<size_t>(player) * P + idx];
    }
    return total;
}

bool is_mixed_action_profile(const Game& g, const double* x, double tol) {
    for (int p = 0; p < g.N; ++p) {
        double sum = 0.0;
        for (int a = 0; a < g.actions[p]; ++a) {
            double v = x[g.offset(p) + a];
            if (!(v >= -tol)) return false;
            sum += v;
        }
        if (std::fabs(sum - 1.0) > tol) return false;
    }
    return true;
}

// Nash equilibrium check: every action in the support is a best response
// (up to `tol`), and the profile lies in the product of simplices.
bool is_nash(const Game& g, const double* x, double tol) {
    if (!is_mixed_action_profile(g, x, tol)) return false;
    for (int p = 0; p < g.N; ++p) {
        double best = -HUGE_VAL;
        std::vector<double> u(g.actions[p]);
        for (int a = 0; a < g.actions[p]; ++a) {
            u[a] = pure_action_payoff(g, p, a, x);
            if (u[a] > best) best = u[a];
        }
        for (int a = 0; a < g.actions[p]; ++a) {
            if (x[g.offset(p) + a] > tol && u[a] < best - tol) return false;
        }
    }
    return true;
}

bool close_profile(const double* x, const std::vector<double>& y, double tol) {
    for (size_t i = 0; i < y.size(); ++i)
        if (std::fabs(x[i] - y[i]) > tol) return false;
    return true;
}

// 3x2 game from von Stengel (2007), as in c_api/README.md, with equilibria
//   ([1, 0, 0], [1, 0]), ([4/5, 1/5, 0], [2/3, 1/3]), ([0, 1/3, 2/3], [1/3, 2/3])
Game von_stengel_3x2() {
    Game g;
    g.N = 2;
    g.actions = {3, 2};
    g.payoffs = {
        3.0, 2.0, 0.0, 3.0, 5.0, 6.0,  // player 1
        3.0, 2.0, 3.0, 2.0, 6.0, 1.0   // player 2
    };
    return g;
}

// 2x2x2 game from McKelvey and McLennan (1996) with 9 Nash equilibria.
Game mckelvey_mclennan_2x2x2() {
    Game g;
    g.N = 3;
    g.actions = {2, 2, 2};
    g.payoffs.assign(3 * 8, 0.0);
    struct Entry { int s[3]; double u[3]; };
    const Entry entries[] = {
        {{0, 0, 0}, {9, 8, 12}},
        {{1, 1, 0}, {9, 8, 2}},
        {{0, 1, 1}, {3, 4, 6}},
        {{1, 0, 1}, {3, 4, 4}},
    };
    for (const Entry& e : entries) {
        std::vector<int> s(e.s, e.s + 3);
        for (int p = 0; p < 3; ++p)
            g.payoffs[static_cast<size_t>(p) * 8 + g.profile_index(s)] = e.u[p];
    }
    return g;
}

// Random 6-player 2-action game on which GNM traces a closed cycle and
// never terminates without an iteration limit (generated by
// `gt -r 6 2 1 1`: payoffs from `makeRandomNFGame(6, 2, 1)`, ray from
// `srand48(1)` normalised). One lap of the cycle is 400 support cells.
Game six_player_cycling_game() {
    Game g;
    g.N = 6;
    g.actions.assign(6, 2);
    static const double payoffs[384] = {
        0.041630344771878214, 0.45449244472862915, 0.8348172181669149, 0.33598603014520023,
        0.5654894035661364, 0.001766912391744313, 0.18758951699996018, 0.9904340799376641,
        0.7504971332295192, 0.36627363815273384, 0.35120909779088194, 0.5733451044556901,
        0.13255423031022318, 0.06416647540187626, 0.9508537336519076, 0.15356010510014784,
        0.5846493665310994, 0.21658811985892612, 0.806501717836408, 0.14047297726302332,
        0.6220587569495315, 0.2108927770064355, 0.0065778848144439905, 0.5732985951291525,
        0.9326642012895014, 0.34032653370951493, 0.8910806352288141, 0.5938725533392599,
        0.3928964668082706, 0.8993232652140506, 0.6949941505989123, 0.228602692238546,
        0.9624593490776796, 0.01205379763140968, 0.11095725048540928, 0.8840964946167063,
        0.11675589085890081, 0.7509225950899321, 0.29693356870572174, 0.6466917194331572,
        0.42657987132955455, 0.5009410124620217, 0.31457721859844057, 0.4367842945153839,
        0.660035610783428, 0.7025457114604166, 0.7748091927743381, 0.8132665881187151,
        0.3198151820656143, 0.9823267424382323, 0.679632712762281, 0.1509747810424713,
        0.8760270919297177, 0.6967586089246396, 0.37736592096032595, 0.564835229210324,
        0.4749922057088476, 0.27249091928155167, 0.939328003835481, 0.25906050374184275,
        0.540183949678454, 0.6477795523764627, 0.5697753638800656, 0.5095652840675982,
        0.20329844975663391, 0.08857618433259518, 0.2808681309283081, 0.7046645220718304,
        0.759929065236367, 0.670620103739779, 0.6070994335637714, 0.3756203540845817,
        0.512246564574216, 0.552193045688, 0.6585107510063999, 0.9378841752893337,
        0.19533377937135654, 0.593231863120323, 0.08184164755743595, 0.5697251702625792,
        0.26739977507537915, 0.9530967897929088, 0.22934156790115523, 0.8017604764184014,
        0.3381362051051333, 0.5849413950771094, 0.9452504548143246, 0.6437441065940206,
        0.9032353815559624, 0.36842564944214473, 0.24200405361748878, 0.48949583538141184,
        0.9139485128790064, 0.329182373216625, 0.8272342025166459, 0.3133465235854871,
        0.9340313394458271, 0.5933412926432027, 0.9869344873295738, 0.38885687887097475,
        0.19613585420843904, 0.5445105388129008, 0.9611926754680233, 0.6503714907480216,
        0.5674187402449071, 0.980514259294182, 0.35122364995519817, 0.9983631970406819,
        0.6497324023419999, 0.8151136316565868, 0.6577654521973919, 0.07929349938284957,
        0.18125082840896667, 0.20874853512978575, 0.1120468246993589, 0.9992769095928296,
        0.859892800940333, 0.6305050138361565, 0.06544263441494635, 0.8482298394906351,
        0.28869700145068933, 0.7051410148885111, 0.3496740664577196, 0.9980720063412392,
        0.1417601242907729, 0.2538162696543651, 0.9061788189607647, 0.716219377132397,
        0.8869780530217248, 0.43052316915415645, 0.2643930154705565, 0.41597647982730024,
        0.5772642650732287, 0.5390806273830862, 0.9805964938867326, 0.7010415310702101,
        0.7619167312413175, 0.004533791824769651, 0.24124684311781763, 0.4953443300673612,
        0.4792474781929634, 0.1001256110596529, 0.5000603528123939, 0.8656333100158164,
        0.403485497037142, 0.6945232676621629, 0.22231023024592034, 0.41702858400959286,
        0.4444466216958922, 0.2971698930278279, 0.7218493341953511, 0.2862013343152725,
        0.6767911797639705, 0.6215913618751188, 0.318296590916912, 0.07859053477844924,
        0.2242444482820254, 0.35194588042652697, 0.9388485046568427, 0.5414148283977553,
        0.2884440398657979, 0.647412096189413, 0.11961006697061904, 0.17009446828485153,
        0.615735113432681, 0.5281461313294216, 0.6066282180031202, 0.28960463281665483,
        0.39001656084704805, 0.7971008383577782, 0.35152613129040944, 0.8024012072802194,
        0.45553187866709166, 0.7212182587385456, 0.27847329408325194, 0.7596823472110756,
        0.3683051053184876, 0.7462302945629347, 0.3590049501631931, 0.0922878654324748,
        0.5848778009440316, 0.9900095431350309, 0.06287027412397705, 0.2715327780158745,
        0.9863653823834717, 0.8542036566668116, 0.40371196762428596, 0.7893852665021441,
        0.34700301172408743, 0.5324890367900963, 0.5181561216822352, 0.22292192724835758,
        0.5598004861301469, 0.461544718759086, 0.909140487177762, 0.2418385461966821,
        0.7763050017081987, 0.35875150553941637, 0.2554770508559976, 0.332501821199763,
        0.7795380774952356, 0.6852663399581616, 0.5993013387829187, 0.740760516781144,
        0.14381113976809345, 0.4467341162239933, 0.033901475894023037, 0.31228254035965364,
        0.12534109426502837, 0.7443301929177153, 0.942265031497481, 0.5579614370233301,
        0.9345154670842426, 0.479553340500658, 0.8004763888451656, 0.5579808744013448,
        0.5535541864792073, 0.9263122999919347, 0.431912104668168, 0.7971028925515284,
        0.6495646200069594, 0.35809610822532534, 0.9532117843878574, 0.8919440885564924,
        0.28809588700312716, 0.6667404215125714, 0.019567703059248487, 0.5153375542029792,
        0.049900547656267946, 0.5584758061121278, 0.08642306348039241, 0.8708863502069661,
        0.09546433953417832, 0.8541709231309369, 0.44176671380970944, 0.4406606444411878,
        0.5878505027761669, 0.061190279871553344, 0.6155566599726363, 0.6794644270221326,
        0.3825322188078566, 0.3969243116779637, 0.28121611560966286, 0.009613004420209847,
        0.8092875968589119, 0.01729556053071235, 0.9725694468197865, 0.17075833046967404,
        0.8201642902691653, 0.2915001914954587, 0.34509150298661595, 0.3806397167740343,
        0.4513680230549433, 0.536635598138858, 0.5131277910388086, 0.18601164102806678,
        0.9661988689749741, 0.9180439556916724, 0.3481250610922295, 0.5403223017091889,
        0.8094838628840826, 0.9841448485612858, 0.883337439048173, 0.8885253139288452,
        0.5380922499929603, 0.05483908927431003, 0.9475125788801897, 0.6128665664786936,
        0.7019532052636244, 0.9524671215647373, 0.35641072653151795, 0.4803878267567754,
        0.5685329950627569, 0.15165052361410858, 0.8924874010658179, 0.007642250815486307,
        0.022102118868946974, 0.6426106608974322, 0.568622919465863, 0.3357635927360647,
        0.6665907727849323, 0.7308460441921056, 0.4234795317580442, 0.09523467340344638,
        0.43477583134226805, 0.7290859895668547, 0.15910480545499794, 0.28075062603073064,
        0.0024722621034278802, 0.3955743160837244, 0.08409841515436867, 0.6893826469641411,
        0.24794928136516958, 0.9119496160184184, 0.04946396700867339, 0.4773575078872554,
        0.43571444134707704, 0.8158796541328002, 0.7937482311894364, 0.7303409920374193,
        0.8699900221105175, 0.2654032594181359, 0.4869224809082162, 0.12793876494765044,
        0.4146533975958313, 0.23648522726867327, 0.3695048565278505, 0.2146200420339781,
        0.5492592670894005, 0.18107481474241638, 0.5186041002991963, 0.006466833561056262,
        0.8892646036373186, 0.5040779489194733, 0.6829539537918485, 0.5967185946380269,
        0.2851196819087143, 0.17383384087811748, 0.26479928865176916, 0.6443078464220022,
        0.4999784222793586, 0.34727986797472, 0.29100996441446725, 0.6003808271381743,
        0.8980513379550139, 0.06897091743597628, 0.21548178722931866, 0.8507075403634516,
        0.7318324102840599, 0.659092437250365, 0.6893060930088204, 0.6200717557646627,
        0.25146005652026204, 0.12179677848054382, 0.7870457102060264, 0.13198264663275694,
        0.5563298066891242, 0.8294515989094009, 0.30256568364411507, 0.6677798816110752,
        0.528895184385096, 0.4341936938797488, 0.5451774740739914, 0.48845218747865005,
        0.3226314027819832, 0.7546331887911606, 0.9484357009190312, 0.12591972821864061,
        0.28777665437523936, 0.6273781314772151, 0.8249721804805255, 0.014432165377392892,
        0.3052158034923913, 0.010599724102434038, 0.7895833412230893, 0.404021038401261,
        0.7343639969066835, 0.10611029579045805, 0.9608493841362495, 0.7041561937262131,
        0.36690090246910145, 0.8189812014235258, 0.7234271120766316, 0.9650554603893866,
        0.29458278103526325, 0.4068127014380849, 0.976518489934616, 0.8752736803321497,
        0.6541272056062475, 0.8572340944823793, 0.7496940299400414, 0.08666561587086363,
        0.09145677602625213, 0.06053650199912397, 0.37918933592348125, 0.6616162375244343,
        0.10566145028505858, 0.6686243036498922, 0.10306489938282581, 0.15322550500687981,
        0.3822769369596024, 0.1214408575076078, 0.6524188312693546, 0.09821205521853216,
    };
    g.payoffs.assign(payoffs, payoffs + 384);
    return g;
}

std::vector<double> six_player_cycling_ray() {
    static const double ray[12] = {
        0.022241210427259465, 0.24281475822985296, 0.4460050840148743, 0.1795021405185878,
        0.3021154133605906, 0.0009439813800884978, 0.10022059496279893, 0.529144135291985,
        0.4009566761140142, 0.19568343968209967, 0.18763513707942162, 0.3063123590619915,
    };
    return std::vector<double>(ray, ray + 12);
}

int call_ipa(const Game& g, const std::vector<double>& ray,
             std::vector<double>& zh, double alpha, double fuzz,
             std::vector<double>& out, int& num_iter,
             int max_iter = 100000, int max_pivots = 1000000) {
    out.assign(g.M(), 0.0);
    num_iter = -1;
    return ipa(g.N, g.actions.data(), g.payoffs.data(), ray.data(), zh.data(),
               alpha, fuzz, out.data(), max_iter, max_pivots, &num_iter);
}

// Returns the number of equilibria (or a negative error code) and fills
// `eqs` with the equilibria, each of length M.
int call_gnm(const Game& g, const std::vector<double>& ray,
             std::vector<std::vector<double> >& eqs, int& num_iter,
             int max_iter = 5000, int steps = 100, double fuzz = 1e-12,
             int lnmfreq = 3, int lnmmax = 10, double lambdamin = -10.0,
             int wobble = 0, double threshold = 1e-2) {
    eqs.clear();
    num_iter = -1;
    double* answers = reinterpret_cast<double*>(0x1);  // must be reset by gnm
    int ret = gnm(g.N, g.actions.data(), g.payoffs.data(), ray.data(), &answers,
                  steps, fuzz, lnmfreq, lnmmax, lambdamin, wobble, threshold,
                  max_iter, &num_iter);
    const int M = g.M();
    if (ret > 0) {
        CHECK(answers != NULL);
        for (int k = 0; k < ret; ++k)
            eqs.push_back(std::vector<double>(answers + k * M, answers + (k + 1) * M));
    } else {
        CHECK(answers == NULL);
    }
    gametracer_free(answers);
    return ret;
}

void test_ipa_von_stengel() {
    Game g = von_stengel_3x2();
    std::vector<double> ray = {0.0, 0.0, 1.0, 0.0, 1.0};
    std::vector<double> zh = {1.0 / 3, 1.0 / 3, 1.0 / 3, 0.5, 0.5};
    std::vector<double> out;
    int num_iter;
    int ret = call_ipa(g, ray, zh, 0.02, 1e-6, out, num_iter);
    CHECK(ret == 1);
    CHECK(is_nash(g, out.data(), 1e-6));
    CHECK(close_profile(out.data(), {0.0, 1.0 / 3, 2.0 / 3, 1.0 / 3, 2.0 / 3}, 1e-6));
    CHECK(num_iter == 1);  // a two-player game is solved in one iteration
}

void test_gnm_von_stengel() {
    Game g = von_stengel_3x2();
    std::vector<double> ray = {0.0, 0.0, 1.0, 0.0, 1.0};
    std::vector<std::vector<double> > eqs;
    int num_iter;
    int ret = call_gnm(g, ray, eqs, num_iter);
    CHECK(ret == 3);
    for (size_t k = 0; k < eqs.size(); ++k)
        CHECK(is_nash(g, eqs[k].data(), 1e-8));
    CHECK(num_iter >= 3);  // at least one crossing per equilibrium found
    // The ray is not modified by the shim
    CHECK(close_profile(ray.data(), {0.0, 0.0, 1.0, 0.0, 1.0}, 0.0));
}

void test_ipa_mckelvey_mclennan() {
    Game g = mckelvey_mclennan_2x2x2();
    std::vector<double> ray = {0.3, 0.7, 0.6, 0.4, 0.2, 0.8};
    std::vector<double> zh(g.M(), 1.0);
    std::vector<double> out;
    int num_iter;
    int ret = call_ipa(g, ray, zh, 0.02, 1e-6, out, num_iter);
    CHECK(ret == 1);
    CHECK(is_nash(g, out.data(), 1e-5));
    CHECK(num_iter > 1);
}

void test_gnm_mckelvey_mclennan() {
    Game g = mckelvey_mclennan_2x2x2();
    std::vector<double> ray = {0.3, 0.7, 0.6, 0.4, 0.2, 0.8};
    std::vector<std::vector<double> > eqs;
    int num_iter;
    int ret = call_gnm(g, ray, eqs, num_iter);
    CHECK(ret > 0);
    CHECK(static_cast<int>(eqs.size()) == ret);
    for (size_t k = 0; k < eqs.size(); ++k)
        CHECK(is_nash(g, eqs[k].data(), 1e-8));
    CHECK(num_iter >= 1);
}

// max_iter: IPA returns 0 with the current approximation (a valid mixed
// action profile) in ans and num_iter == max_iter; with a sufficient limit
// it converges. max_pivots: a too small limit makes IPA give up.
void test_ipa_limits() {
    Game g = mckelvey_mclennan_2x2x2();
    std::vector<double> ray = {0.3, 0.7, 0.6, 0.4, 0.2, 0.8};
    std::vector<double> out;
    int num_iter;

    // Reference run
    std::vector<double> zh(g.M(), 1.0);
    int ret = call_ipa(g, ray, zh, 0.02, 1e-6, out, num_iter);
    CHECK(ret == 1);
    const int needed = num_iter;
    CHECK(needed > 10);

    // Iteration limit reached
    for (int cap = 1; cap <= 10; cap += 9) {
        zh.assign(g.M(), 1.0);
        ret = call_ipa(g, ray, zh, 0.02, 1e-6, out, num_iter, cap);
        CHECK(ret == 0);
        CHECK(num_iter == cap);
        CHECK(is_mixed_action_profile(g, out.data(), 1e-12));
    }

    // Exactly enough iterations
    zh.assign(g.M(), 1.0);
    ret = call_ipa(g, ray, zh, 0.02, 1e-6, out, num_iter, needed);
    CHECK(ret == 1);
    CHECK(num_iter == needed);
    CHECK(is_nash(g, out.data(), 1e-5));

    // Pivot limit: the three-player run needs more than 2 pivots in some
    // Lemke-Howson solve; on giving up, ans holds the last iterate
    zh.assign(g.M(), 1.0);
    ret = call_ipa(g, ray, zh, 0.02, 1e-6, out, num_iter, 100000, 2);
    CHECK(ret == 0);
    CHECK(num_iter >= 1 && num_iter < needed);
    CHECK(is_mixed_action_profile(g, out.data(), 1e-12));

    // The Lemke-Howson path of the 3x2 game has exactly 5 pivots (the
    // entry pivot included)
    Game g2 = von_stengel_3x2();
    std::vector<double> ray2 = {0.0, 0.0, 1.0, 0.0, 1.0};
    std::vector<double> zh2 = {1.0 / 3, 1.0 / 3, 1.0 / 3, 0.5, 0.5};
    ret = call_ipa(g2, ray2, zh2, 0.02, 1e-6, out, num_iter, 100000, 4);
    CHECK(ret == 0);
    CHECK(num_iter == 1);
    CHECK(is_mixed_action_profile(g2, out.data(), 1e-12));
    zh2 = {1.0 / 3, 1.0 / 3, 1.0 / 3, 0.5, 0.5};
    ret = call_ipa(g2, ray2, zh2, 0.02, 1e-6, out, num_iter, 100000, 5);
    CHECK(ret == 1);
    CHECK(is_nash(g2, out.data(), 1e-6));

    // Giving up during the last allowed iteration also leaves
    // num_iter == max_iter, so the equality does not identify the limit
    zh2 = {1.0 / 3, 1.0 / 3, 1.0 / 3, 0.5, 0.5};
    ret = call_ipa(g2, ray2, zh2, 0.02, 1e-6, out, num_iter, 1, 4);
    CHECK(ret == 0);
    CHECK(num_iter == 1);
}

// max_iter: GNM returns the equilibria found so far and num_iter == max_iter
// when the limit is reached; the first few crossings of the 3x2 game find
// its three equilibria one by one.
void test_gnm_limits() {
    Game g = von_stengel_3x2();
    std::vector<double> ray = {0.0, 0.0, 1.0, 0.0, 1.0};
    std::vector<std::vector<double> > eqs;
    int num_iter;

    int ret = call_gnm(g, ray, eqs, num_iter);
    CHECK(ret == 3);
    const int needed = num_iter;
    CHECK(needed > 3);

    int prev = 0;
    for (int cap = 1; cap < needed; ++cap) {
        ret = call_gnm(g, ray, eqs, num_iter, cap);
        CHECK(ret >= 0 && ret <= 3);
        CHECK(ret >= prev);  // equilibria are found in path order
        CHECK(num_iter == cap);
        for (size_t k = 0; k < eqs.size(); ++k)
            CHECK(is_nash(g, eqs[k].data(), 1e-8));
        prev = ret;
    }
    CHECK(prev < 3);  // the last crossing is needed for the third equilibrium

    ret = call_gnm(g, ray, eqs, num_iter, needed);
    CHECK(ret == 3);
    CHECK(num_iter == needed);

    // Three players (nonlinear path within a cell): a capped run returns
    // the equilibria found so far; a cap equal to the number of cells the
    // path needs returns everything with num_iter == max_iter, so the
    // equality does not identify the limit
    Game g3 = mckelvey_mclennan_2x2x2();
    std::vector<double> ray3 = {0.3, 0.7, 0.6, 0.4, 0.2, 0.8};
    std::vector<std::vector<double> > eqs3;
    int num_iter3;
    int ret3 = call_gnm(g3, ray3, eqs3, num_iter3);
    CHECK(ret3 > 1);
    const int needed3 = num_iter3;
    CHECK(needed3 > 1);
    ret = call_gnm(g3, ray3, eqs, num_iter, 1);
    CHECK(ret >= 0 && ret < ret3);
    CHECK(num_iter == 1);
    for (size_t k = 0; k < eqs.size(); ++k)
        CHECK(is_nash(g3, eqs[k].data(), 1e-8));
    ret = call_gnm(g3, ray3, eqs, num_iter, needed3);
    CHECK(ret == ret3);
    CHECK(num_iter == needed3);
}

// The motivating case: without a limit GNM traces this game's path forever,
// appending the same equilibria on every lap; max_iter stops it.
void test_gnm_cycling_game() {
    Game g = six_player_cycling_game();
    std::vector<double> ray = six_player_cycling_ray();
    std::vector<std::vector<double> > eqs;
    int num_iter;

    int ret = call_gnm(g, ray, eqs, num_iter, 500);
    CHECK(ret > 0);
    CHECK(num_iter == 500);
    CHECK(static_cast<int>(eqs.size()) == ret);
    for (size_t k = 0; k < eqs.size(); ++k)
        CHECK(is_nash(g, eqs[k].data(), 1e-8));
}

void test_invalid_arguments() {
    Game g = von_stengel_3x2();
    std::vector<double> ray(g.M(), 1.0), zh(g.M(), 1.0), out(g.M());
    double* answers = NULL;

    // null pointers
    CHECK(ipa(g.N, NULL, g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
    CHECK(ipa(g.N, g.actions.data(), NULL, ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
    CHECK(ipa(g.N, g.actions.data(), g.payoffs.data(), NULL, zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
    CHECK(ipa(g.N, g.actions.data(), g.payoffs.data(), ray.data(), NULL, 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
    CHECK(ipa(g.N, g.actions.data(), g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, NULL, 100000, 1000000, NULL) == -1);
    CHECK(gnm(g.N, NULL, g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);
    CHECK(answers == NULL);
    CHECK(gnm(g.N, g.actions.data(), g.payoffs.data(), ray.data(), NULL, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);

    // fewer than two players
    {
        int actions1[] = {3};
        double payoffs1[] = {1.0, 2.0, 3.0};
        double ray1[] = {0.1, 0.2, 0.3}, zh1[] = {1.0, 1.0, 1.0}, out1[3];
        CHECK(ipa(1, actions1, payoffs1, ray1, zh1, 0.02, 1e-6, out1, 100000, 1000000, NULL) == -1);
        CHECK(gnm(1, actions1, payoffs1, ray1, &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);
        CHECK(answers == NULL);
        CHECK(ipa(0, actions1, payoffs1, ray1, zh1, 0.02, 1e-6, out1, 100000, 1000000, NULL) == -1);
    }

    // non-positive action counts
    {
        int bad_actions[] = {3, 0};
        CHECK(ipa(2, bad_actions, g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
        CHECK(gnm(2, bad_actions, g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);
    }

    // size overflow
    {
        int huge_actions[] = {INT_MAX, INT_MAX};
        CHECK(ipa(2, huge_actions, g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
        CHECK(gnm(2, huge_actions, g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);
    }

    // M = 65536 passes the M, P, N*P checks but M*M overflows int in the core
    {
        int big_actions[] = {65535, 1};
        CHECK(ipa(2, big_actions, g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
        CHECK(gnm(2, big_actions, g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);
        CHECK(answers == NULL);
    }

    // N*P = 32 * 2^27 = 2^32 exceeds INT_MAX; on a 32-bit size_t the
    // product wraps to 0, so it must be checked before multiplying
    {
        int many_actions[32];
        for (int p = 0; p < 32; ++p) many_actions[p] = (p < 27) ? 2 : 1;
        CHECK(ipa(32, many_actions, g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == -1);
        CHECK(gnm(32, many_actions, g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) == -1);
        CHECK(answers == NULL);
    }

    // iteration limits must be positive; num_iter may be NULL
    {
        int num_iter = 7;
        CHECK(ipa(g.N, g.actions.data(), g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 0, 1000000, &num_iter) == -1);
        CHECK(num_iter == 0);
        CHECK(ipa(g.N, g.actions.data(), g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 0, NULL) == -1);
        num_iter = 7;
        CHECK(gnm(g.N, g.actions.data(), g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 0, &num_iter) == -1);
        CHECK(num_iter == 0);
        CHECK(answers == NULL);
        CHECK(ipa(g.N, g.actions.data(), g.payoffs.data(), ray.data(), zh.data(), 0.02, 1e-6, out.data(), 100000, 1000000, NULL) == 1);
        // (the all-ones ray is a degenerate perturbation for GNM, which then
        // finds no equilibria; only the NULL num_iter acceptance is tested)
        CHECK(gnm(g.N, g.actions.data(), g.payoffs.data(), ray.data(), &answers, 100, 1e-12, 3, 10, -10.0, 0, 1e-2, 5000, NULL) >= 0);
        gametracer_free(answers);
        answers = NULL;
    }

    // gametracer_free is safe on NULL
    gametracer_free(NULL);
}

}  // namespace

int main() {
    test_ipa_von_stengel();
    test_gnm_von_stengel();
    test_ipa_mckelvey_mclennan();
    test_gnm_mckelvey_mclennan();
    test_ipa_limits();
    test_gnm_limits();
    test_gnm_cycling_game();
    test_invalid_arguments();

    if (g_failures == 0) {
        std::printf("All C API tests passed.\n");
        return EXIT_SUCCESS;
    }
    std::printf("%d check(s) failed.\n", g_failures);
    return EXIT_FAILURE;
}
